# LuaWorld - This file is licensed under AGPLv3
# Copyright (c) 2025 LuaWorld Contributors
# See AGPLv3.txt for details.

- type: job
  id: OutpostSyndicateMedic
  name: job-name-typan-medic
  playTimeTracker: JobOutpostTypanMedic
  salary: 35000
  description: Медик из далёкого космоса.
  startingGear: SyndicateParamedic
  icon: "JobIconSyndicateParamedic"
  supervisors: job-supervisors-typan-telecommunications-officer
  canBeAntag: false
  hideConsoleVisibility: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobOutpostTypanBotanist
    #   time: 20600
    - !type:DepartmentTimeRequirement
      department: Antag
      time: 31000
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 18000
    - !type:DepartmentTimeRequirement
      department: Security
      time: 72000 # 20 hours
    - !type:OverallPlaytimeRequirement
      time: 360000
  access:
  - SyndicateAgent
  - NuclearOperative
  accessGroups:
  - AllAccess
  special:
  - !type:AddComponentSpecial
    components:
      - type: Company
        companyName: Syndicate
      - type: SpecialSectorStationRecord
        recordGeneration: FalseRecord
      - type: MailDisabled

- type: startingGear
  id: SyndicateParamedic
  equipment:
    eyes: ClothingEyesHudSyndicateAgentOutpostSyndicate
    ears: ClothingHeadsetAltOutpostSyndicate
    jumpsuit: ClothingUniformJumpsuitParamedicSyndie
    outerClothing: ClothingOuterMedOutpostSyndicate
    shoes: ClothingShoesBootsCombat
    id: MedicalPDASyndi
    back: ClothingBackpackSyndicateFilled
    belt: ClothingBeltMedicalFilled
