# LuaWorld - This file is licensed under AGPLv3
# Copyright (c) 2025 LuaWorld Contributors
# See AGPLv3.txt for details.

- type: job
  id: OutpostSyndicateRD
  name: job-name-typan-rd
  playTimeTracker: JobOutpostTypanRD
  salary: 45000
  description: Директор исследований из далёкого космоса.
  startingGear: SyndicateRD
  icon: "JobIconSyndicateRD"
  supervisors: job-supervisors-typan-syndicate
  canBeAntag: false
  hideConsoleVisibility: true
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 32000
    - !type:DepartmentTimeRequirement
      department: Antag
      time: 34000
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 73000
    - !type:DepartmentTimeRequirement
      department: Frontier
      time: 83000
    - !type:OverallPlaytimeRequirement
      time: 150000
  access:
  - SyndicateAgent
  - NuclearOperative
  - ResearchDirectorTypan
  accessGroups:
  - AllAccess
  special:
  - !type:AddComponentSpecial
    components:
      - type: Company
        companyName: Syndicate
      - type: SpecialSectorStationRecord
        recordGeneration: FalseRecord
      - type: MailDisabled

- type: startingGear
  id: SyndicateRD
  equipment:
    eyes: ClothingEyesGlassesHiddenSecurity
    ears: ClothingHeadsetAltOutpostSyndicate
    shoes: ClothingShoesBootsCombat
    outerClothing: ClothingOuterCoatRDOutpostSyndicate
    gloves: ClothingHandsRDOutpostSyndicate
    id: SyndiPDARD
    back: ClothingBackpackSyndicateFilled
    jumpsuit: ClothingUniformJumpsuitSyndieFormal
    belt: ClothingBeltAssaultOutpostSyndicate
