# LuaWorld - This file is licensed under AGPLv3
# Copyright (c) 2025 LuaWorld Contributors
# See AGPLv3.txt for details.

- type: job
  id: OutpostSyndicateResearcher
  name: job-name-typan-researcher
  playTimeTracker: JobOutpostTypanResearcher
  salary: 25000
  description: Исследователь из далёкого космоса.
  startingGear: SyndicateResearcher
  icon: "JobIconSyndicateResearcher"
  supervisors: job-supervisors-typan-telecommunications-officer
  canBeAntag: false
  hideConsoleVisibility: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobOutpostTypanAtmosTech
    #   time: 29600
    # - !type:RoleTimeRequirement
    #   role: JobOutpostTypanMedic
    #   time: 25600
    # - !type:RoleTimeRequirement
    #   role: JobOutpostTypanScience
    #   time: 32500
    # - !type:RoleTimeRequirement
    #   role: JobOutpostTypanBotanist
    #   time: 33600
    - !type:DepartmentTimeRequirement
      department: Security
      time: 39000
    - !type:DepartmentTimeRequirement
      department: Antag
      time: 36000
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 43000
    - !type:OverallPlaytimeRequirement
      time: 360000
  access:
  - SyndicateAgent
  - NuclearOperative
  accessGroups:
  - AllAccess
  special:
  - !type:AddComponentSpecial
    components:
      - type: Company
        companyName: Syndicate
      - type: SpecialSectorStationRecord
        recordGeneration: FalseRecord
      - type: MailDisabled

- type: startingGear
  id: SyndicateResearcher
  equipment:
    ears: ClothingHeadsetAltOutpostSyndicate
    jumpsuit: ClothingUniformJumpsuitRecruitSyndie
    shoes: ClothingShoesBootsOutpostSyndicate
    back: ClothingBackpackSyndicateFilled
    belt: ClothingBeltAssaultOutpostSyndicate

    id: SyndiPDAResearcher
