- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Amber
  - Bagel
  - Box
  - Convex
  #- Core
  - Elkridge
  - Fland
  - Gate
  - Loop
  - Marathon
  - Meta
  - Oasis
  - Omega
  - Packed
  - Plasma
  - Reach
  - Train

- type: gameMapPool
  id: ShipVsShip
  maps:
  - ShipVsShip

- type: gameMapPool
  id: Dev
  maps:
  - Dev

