- type: department
  id: SpacePrison
  sort: 0
  name: department-prison
  description: department-pison-description
  color: "#9f4000"
#  weight: -5
  roles:
  - HeadOfPrison
  - DHPrisonGuard
  - PermaPrisoner
  - PrisonDoctor
  - PrisonDoctorTest
